### ISSUE TITLE
HTTPS with self-signed SSL cert doesn't work

### ISSUE THREAD

**Issue by MoriTanosuke** [phubbard/Meltdown#1]
I'm using Fever on https://kopis.de/fever and my SSL cert isn't accepted by Google Chrome, so I see the red warning every time I open the page.

Looks like this is causing problems with Meltdown, because I can't use HTTPS when I set up my server. I know that there is a way to ignore the warning because Apps like [CalDAV sync](https://play.google.com/store/apps/details?id=org.dmfs.caldav.lib) can use my HTTPS host.

**Comment by phubbard** [comment]
SSL support is next on the dev list; as you noticed it's broken right now.

**Comment by phubbard** [comment]
OK, I rewrote the transport layer to use httpurlconnection, which handles SSL. Tested and verified with a godaddy cert, so all you need to do now is import your CA cert into the device. See

http://android.stackexchange.com/questions/4039/how-to-install-a-web-certificate-on-an-android-device
