### ISSUE TITLE
Meltdown is the No 1 data consumer on my phone

### ISSUE THREAD

**Issue by MoriTanosuke** [phubbard/Meltdown#3]
The data usage report shows Meltdown at the top on my phone. I think that's because of the 15min update interval. I'd like to have that configurable.

Right now I disable background data usage for meltdown to avoid this.

**Comment by MoriTanosuke** [comment]
This is the place where the `Downloader` starts up: https://github.com/MoriTanosuke/Meltdown/blob/master/src/net/phfactor/meltdown/MeltdownApp.java#L711

I already saw that `Downloader` has a _TODO_ to make the interval a preference: https://github.com/MoriTanosuke/Meltdown/blob/master/src/net/phfactor/meltdown/Downloader.java#L13

**Comment by phubbard** [comment]
OK, implemented and committed. (Though I suspect I will have more work on the manual update option). Code is uploaded to Google Play as v0.8.3 build 53.

**Comment by MoriTanosuke** [comment]
Wow, that's quick again. I was just thinking about implementing it myself.
:-) I'm going to update as soon as it's available.

**Comment by phubbard** [comment]
Turned out to touch a lot of code and files (prefs, menu, config file, service) so there may be new bugs. Do send crash reports and file bugs here please.

**Comment by MoriTanosuke** [comment]
Sure, will do.
