### ISSUE TITLE
Orphaned feeds group not working

### ISSUE THREAD

**Issue by phubbard** [phubbard/Meltdown#7]
New install, on a server with items but no groups, does not assign items to the orphaned feeds group as it should.

**Comment by flurischt** [comment]
I think this ticket and my pull request in ticket #10 describe the same problem. should "Kindling" feeds without a group be added to orphaned?

**Comment by phubbard** [comment]
I think so but am not certain. I'll cut a release with kindling and see how it works.

**Comment by phubbard** [comment]
Should be fixed in 0.9.4 - if not, file a new bug.
